[project]
name = "archette"
version = "0.1.1"
description = "tiny arch"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numba>=0.53.1",
    "numpy>=2.0.2",
    "scipy>=1.13.1",
]
